# This workflow will build and test a Swift project using xcodebuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build with xcodebuild
      run: |
        xcodebuild -scheme DailyPic -destination 'platform=macOS' -derivedDataPath ./build build

    - name: Run tests
      run: |
        xcodebuild -scheme DailyPic -destination 'platform=macOS' test
