# This workflow will build and test a Swift project using xcodebuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0'

    - name: Build with xcodebuild
      run: |
        xcodebuild -scheme "DailyPic" -destination 'platform=macOS' -derivedDataPath ./build build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DailyPic-Build
        path: ./build/Build/Products/Debug/
